### PR TITLE
test(setup.py): Add test requirements

### PR DESCRIPTION
**Pull request by Rizhiy**
Includes #11, #12, #13 and adds a few improvements IMHO:
* Sort imports using `isort`
* Format code to one standard using `black`
* Add GitHub workflow to automatically run tests. Afterwards can add badges to `README.md` and automatic deployment to `pypy`.

While this is not required to fix any issues, I would say this would be an improvement to the project.

### CODE REVIEW

**Review by vthorey — APPROVED** [review]
Thank you for your contribution. I merged the separate PRs so it created conflicts here. Otherwise, feel free to merge.

**Comment by Rizhiy** [comment]
I resolved the conflicts, but I don't think I have merge rights (at least I can't find the button).

**Comment by Rizhiy** [comment]
Also, does the package on PyPy get updated automatically or do you have to do it manually?

**Comment by Rizhiy** [comment]
Started using the new version and found that I actually forgot to fix the original issue.
Should be done now, added a basic test as well.

**Comment by vthorey** [comment]
> Also, does the package on PyPy get updated automatically or do you have to do it manually?

I have to manually update as of now ;)

**Pull request merged**
